#ifndef ASTEROIDS_SETTINGS_HH
#define ASTEROIDS_SETTINGS_HH

class Settings {
	public:

		bool DISPLAY_FULLSCREEN;
		bool INVERT_PITCH;

		int RESOLUTION_X;
		int RESOLUTION_Y;
		int MAX_FPS;

		double GRAVITATION_CONSTANT;
		double ACCELERATION_SPEED;
		double TURN_SPEED;
		double MOUSE_SENSITIVITY;
		double GUN_COOLDOWN;
		double PROJECTILE_SPEED;
		double PROJECTILE_LIFETIME;

		Settings() {
			DISPLAY_FULLSCREEN = false;
			RESOLUTION_X = 1280;
			RESOLUTION_Y = 800;
			MAX_FPS = 100;
			GRAVITATION_CONSTANT = 100.0;
			INVERT_PITCH = false;
			ACCELERATION_SPEED = 100.0;
			TURN_SPEED = 100.0;
			MOUSE_SENSITIVITY = 70.0;
			GUN_COOLDOWN = 0.12;
			PROJECTILE_SPEED = 4000.0;
			PROJECTILE_LIFETIME = 10.0;
		}
};

#endif
